// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "single_conv_calculat.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic single_conv_calculat::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic single_conv_calculat::ap_const_logic_0 = sc_dt::Log_0;
const bool single_conv_calculat::ap_const_boolean_1 = true;
const bool single_conv_calculat::ap_const_boolean_0 = false;

single_conv_calculat::single_conv_calculat(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln34_1_fu_184_p2);
    sensitive << ( mul_ln34_2_reg_239 );
    sensitive << ( mul_ln34_3_reg_244 );

    SC_METHOD(thread_add_ln34_2_fu_188_p2);
    sensitive << ( add_ln34_1_fu_184_p2 );
    sensitive << ( add_ln34_fu_180_p2 );

    SC_METHOD(thread_add_ln34_3_fu_171_p2);
    sensitive << ( mul_ln34_4_reg_214 );
    sensitive << ( mul_ln34_5_reg_219 );

    SC_METHOD(thread_add_ln34_4_fu_106_p2);
    sensitive << ( mul_ln34_7_reg_204 );
    sensitive << ( mul_ln34_8_reg_209 );

    SC_METHOD(thread_add_ln34_5_fu_110_p2);
    sensitive << ( mul_ln34_6_reg_199 );
    sensitive << ( add_ln34_4_fu_106_p2 );

    SC_METHOD(thread_add_ln34_6_fu_175_p2);
    sensitive << ( add_ln34_5_reg_224 );
    sensitive << ( add_ln34_3_fu_171_p2 );

    SC_METHOD(thread_add_ln34_7_fu_194_p2);
    sensitive << ( add_ln34_6_reg_249 );
    sensitive << ( add_ln34_2_fu_188_p2 );

    SC_METHOD(thread_add_ln34_fu_180_p2);
    sensitive << ( mul_ln34_reg_229 );
    sensitive << ( mul_ln34_1_reg_234 );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_return);
    sensitive << ( add_ln34_7_fu_194_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_int_reg );

    SC_METHOD(thread_mul_ln34_1_fu_137_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( cal_conv_0_1_int_reg );

    SC_METHOD(thread_mul_ln34_1_fu_137_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( kernel_0_1_int_reg );

    SC_METHOD(thread_mul_ln34_1_fu_137_p2);
    sensitive << ( mul_ln34_1_fu_137_p0 );
    sensitive << ( mul_ln34_1_fu_137_p1 );

    SC_METHOD(thread_mul_ln34_2_fu_151_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( cal_conv_0_2_int_reg );

    SC_METHOD(thread_mul_ln34_2_fu_151_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( kernel_0_2_int_reg );

    SC_METHOD(thread_mul_ln34_2_fu_151_p2);
    sensitive << ( mul_ln34_2_fu_151_p0 );
    sensitive << ( mul_ln34_2_fu_151_p1 );

    SC_METHOD(thread_mul_ln34_3_fu_165_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( cal_conv_1_0_int_reg );

    SC_METHOD(thread_mul_ln34_3_fu_165_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( kernel_1_0_int_reg );

    SC_METHOD(thread_mul_ln34_3_fu_165_p2);
    sensitive << ( mul_ln34_3_fu_165_p0 );
    sensitive << ( mul_ln34_3_fu_165_p1 );

    SC_METHOD(thread_mul_ln34_4_fu_86_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( cal_conv_1_1_int_reg );

    SC_METHOD(thread_mul_ln34_4_fu_86_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( kernel_1_1_int_reg );

    SC_METHOD(thread_mul_ln34_4_fu_86_p2);
    sensitive << ( mul_ln34_4_fu_86_p0 );
    sensitive << ( mul_ln34_4_fu_86_p1 );

    SC_METHOD(thread_mul_ln34_5_fu_100_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( cal_conv_1_2_int_reg );

    SC_METHOD(thread_mul_ln34_5_fu_100_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( kernel_1_2_int_reg );

    SC_METHOD(thread_mul_ln34_5_fu_100_p2);
    sensitive << ( mul_ln34_5_fu_100_p0 );
    sensitive << ( mul_ln34_5_fu_100_p1 );

    SC_METHOD(thread_mul_ln34_6_fu_44_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( cal_conv_2_0_int_reg );

    SC_METHOD(thread_mul_ln34_6_fu_44_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( kernel_2_0_int_reg );

    SC_METHOD(thread_mul_ln34_6_fu_44_p2);
    sensitive << ( mul_ln34_6_fu_44_p0 );
    sensitive << ( mul_ln34_6_fu_44_p1 );

    SC_METHOD(thread_mul_ln34_7_fu_58_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( cal_conv_2_1_int_reg );

    SC_METHOD(thread_mul_ln34_7_fu_58_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( kernel_2_1_int_reg );

    SC_METHOD(thread_mul_ln34_7_fu_58_p2);
    sensitive << ( mul_ln34_7_fu_58_p0 );
    sensitive << ( mul_ln34_7_fu_58_p1 );

    SC_METHOD(thread_mul_ln34_8_fu_72_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( cal_conv_2_2_int_reg );

    SC_METHOD(thread_mul_ln34_8_fu_72_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( kernel_2_2_int_reg );

    SC_METHOD(thread_mul_ln34_8_fu_72_p2);
    sensitive << ( mul_ln34_8_fu_72_p0 );
    sensitive << ( mul_ln34_8_fu_72_p1 );

    SC_METHOD(thread_mul_ln34_fu_123_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( cal_conv_0_0_int_reg );

    SC_METHOD(thread_mul_ln34_fu_123_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( kernel_0_0_int_reg );

    SC_METHOD(thread_mul_ln34_fu_123_p2);
    sensitive << ( mul_ln34_fu_123_p0 );
    sensitive << ( mul_ln34_fu_123_p1 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "single_conv_calculat_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, cal_conv_0_0, "(port)cal_conv_0_0");
    sc_trace(mVcdFile, kernel_0_0, "(port)kernel_0_0");
    sc_trace(mVcdFile, cal_conv_0_1, "(port)cal_conv_0_1");
    sc_trace(mVcdFile, kernel_0_1, "(port)kernel_0_1");
    sc_trace(mVcdFile, cal_conv_0_2, "(port)cal_conv_0_2");
    sc_trace(mVcdFile, kernel_0_2, "(port)kernel_0_2");
    sc_trace(mVcdFile, cal_conv_1_0, "(port)cal_conv_1_0");
    sc_trace(mVcdFile, kernel_1_0, "(port)kernel_1_0");
    sc_trace(mVcdFile, cal_conv_1_1, "(port)cal_conv_1_1");
    sc_trace(mVcdFile, kernel_1_1, "(port)kernel_1_1");
    sc_trace(mVcdFile, cal_conv_1_2, "(port)cal_conv_1_2");
    sc_trace(mVcdFile, kernel_1_2, "(port)kernel_1_2");
    sc_trace(mVcdFile, cal_conv_2_0, "(port)cal_conv_2_0");
    sc_trace(mVcdFile, kernel_2_0, "(port)kernel_2_0");
    sc_trace(mVcdFile, cal_conv_2_1, "(port)cal_conv_2_1");
    sc_trace(mVcdFile, kernel_2_1, "(port)kernel_2_1");
    sc_trace(mVcdFile, cal_conv_2_2, "(port)cal_conv_2_2");
    sc_trace(mVcdFile, kernel_2_2, "(port)kernel_2_2");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, mul_ln34_6_fu_44_p2, "mul_ln34_6_fu_44_p2");
    sc_trace(mVcdFile, mul_ln34_6_reg_199, "mul_ln34_6_reg_199");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, mul_ln34_7_fu_58_p2, "mul_ln34_7_fu_58_p2");
    sc_trace(mVcdFile, mul_ln34_7_reg_204, "mul_ln34_7_reg_204");
    sc_trace(mVcdFile, mul_ln34_8_fu_72_p2, "mul_ln34_8_fu_72_p2");
    sc_trace(mVcdFile, mul_ln34_8_reg_209, "mul_ln34_8_reg_209");
    sc_trace(mVcdFile, mul_ln34_4_fu_86_p2, "mul_ln34_4_fu_86_p2");
    sc_trace(mVcdFile, mul_ln34_4_reg_214, "mul_ln34_4_reg_214");
    sc_trace(mVcdFile, mul_ln34_5_fu_100_p2, "mul_ln34_5_fu_100_p2");
    sc_trace(mVcdFile, mul_ln34_5_reg_219, "mul_ln34_5_reg_219");
    sc_trace(mVcdFile, add_ln34_5_fu_110_p2, "add_ln34_5_fu_110_p2");
    sc_trace(mVcdFile, add_ln34_5_reg_224, "add_ln34_5_reg_224");
    sc_trace(mVcdFile, mul_ln34_fu_123_p2, "mul_ln34_fu_123_p2");
    sc_trace(mVcdFile, mul_ln34_reg_229, "mul_ln34_reg_229");
    sc_trace(mVcdFile, mul_ln34_1_fu_137_p2, "mul_ln34_1_fu_137_p2");
    sc_trace(mVcdFile, mul_ln34_1_reg_234, "mul_ln34_1_reg_234");
    sc_trace(mVcdFile, mul_ln34_2_fu_151_p2, "mul_ln34_2_fu_151_p2");
    sc_trace(mVcdFile, mul_ln34_2_reg_239, "mul_ln34_2_reg_239");
    sc_trace(mVcdFile, mul_ln34_3_fu_165_p2, "mul_ln34_3_fu_165_p2");
    sc_trace(mVcdFile, mul_ln34_3_reg_244, "mul_ln34_3_reg_244");
    sc_trace(mVcdFile, add_ln34_6_fu_175_p2, "add_ln34_6_fu_175_p2");
    sc_trace(mVcdFile, add_ln34_6_reg_249, "add_ln34_6_reg_249");
    sc_trace(mVcdFile, mul_ln34_6_fu_44_p0, "mul_ln34_6_fu_44_p0");
    sc_trace(mVcdFile, mul_ln34_6_fu_44_p1, "mul_ln34_6_fu_44_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, mul_ln34_7_fu_58_p0, "mul_ln34_7_fu_58_p0");
    sc_trace(mVcdFile, mul_ln34_7_fu_58_p1, "mul_ln34_7_fu_58_p1");
    sc_trace(mVcdFile, mul_ln34_8_fu_72_p0, "mul_ln34_8_fu_72_p0");
    sc_trace(mVcdFile, mul_ln34_8_fu_72_p1, "mul_ln34_8_fu_72_p1");
    sc_trace(mVcdFile, mul_ln34_4_fu_86_p0, "mul_ln34_4_fu_86_p0");
    sc_trace(mVcdFile, mul_ln34_4_fu_86_p1, "mul_ln34_4_fu_86_p1");
    sc_trace(mVcdFile, mul_ln34_5_fu_100_p0, "mul_ln34_5_fu_100_p0");
    sc_trace(mVcdFile, mul_ln34_5_fu_100_p1, "mul_ln34_5_fu_100_p1");
    sc_trace(mVcdFile, add_ln34_4_fu_106_p2, "add_ln34_4_fu_106_p2");
    sc_trace(mVcdFile, mul_ln34_fu_123_p0, "mul_ln34_fu_123_p0");
    sc_trace(mVcdFile, mul_ln34_fu_123_p1, "mul_ln34_fu_123_p1");
    sc_trace(mVcdFile, mul_ln34_1_fu_137_p0, "mul_ln34_1_fu_137_p0");
    sc_trace(mVcdFile, mul_ln34_1_fu_137_p1, "mul_ln34_1_fu_137_p1");
    sc_trace(mVcdFile, mul_ln34_2_fu_151_p0, "mul_ln34_2_fu_151_p0");
    sc_trace(mVcdFile, mul_ln34_2_fu_151_p1, "mul_ln34_2_fu_151_p1");
    sc_trace(mVcdFile, mul_ln34_3_fu_165_p0, "mul_ln34_3_fu_165_p0");
    sc_trace(mVcdFile, mul_ln34_3_fu_165_p1, "mul_ln34_3_fu_165_p1");
    sc_trace(mVcdFile, add_ln34_3_fu_171_p2, "add_ln34_3_fu_171_p2");
    sc_trace(mVcdFile, add_ln34_1_fu_184_p2, "add_ln34_1_fu_184_p2");
    sc_trace(mVcdFile, add_ln34_fu_180_p2, "add_ln34_fu_180_p2");
    sc_trace(mVcdFile, add_ln34_2_fu_188_p2, "add_ln34_2_fu_188_p2");
    sc_trace(mVcdFile, add_ln34_7_fu_194_p2, "add_ln34_7_fu_194_p2");
    sc_trace(mVcdFile, ap_ce_reg, "ap_ce_reg");
    sc_trace(mVcdFile, cal_conv_0_0_int_reg, "cal_conv_0_0_int_reg");
    sc_trace(mVcdFile, kernel_0_0_int_reg, "kernel_0_0_int_reg");
    sc_trace(mVcdFile, cal_conv_0_1_int_reg, "cal_conv_0_1_int_reg");
    sc_trace(mVcdFile, kernel_0_1_int_reg, "kernel_0_1_int_reg");
    sc_trace(mVcdFile, cal_conv_0_2_int_reg, "cal_conv_0_2_int_reg");
    sc_trace(mVcdFile, kernel_0_2_int_reg, "kernel_0_2_int_reg");
    sc_trace(mVcdFile, cal_conv_1_0_int_reg, "cal_conv_1_0_int_reg");
    sc_trace(mVcdFile, kernel_1_0_int_reg, "kernel_1_0_int_reg");
    sc_trace(mVcdFile, cal_conv_1_1_int_reg, "cal_conv_1_1_int_reg");
    sc_trace(mVcdFile, kernel_1_1_int_reg, "kernel_1_1_int_reg");
    sc_trace(mVcdFile, cal_conv_1_2_int_reg, "cal_conv_1_2_int_reg");
    sc_trace(mVcdFile, kernel_1_2_int_reg, "kernel_1_2_int_reg");
    sc_trace(mVcdFile, cal_conv_2_0_int_reg, "cal_conv_2_0_int_reg");
    sc_trace(mVcdFile, kernel_2_0_int_reg, "kernel_2_0_int_reg");
    sc_trace(mVcdFile, cal_conv_2_1_int_reg, "cal_conv_2_1_int_reg");
    sc_trace(mVcdFile, kernel_2_1_int_reg, "kernel_2_1_int_reg");
    sc_trace(mVcdFile, cal_conv_2_2_int_reg, "cal_conv_2_2_int_reg");
    sc_trace(mVcdFile, kernel_2_2_int_reg, "kernel_2_2_int_reg");
    sc_trace(mVcdFile, ap_return_int_reg, "ap_return_int_reg");
#endif

    }
}

single_conv_calculat::~single_conv_calculat() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void single_conv_calculat::thread_ap_clk_no_reset_() {
    ap_ce_reg = ap_ce.read();
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_ce_reg.read(), ap_const_logic_1))) {
        add_ln34_5_reg_224 = add_ln34_5_fu_110_p2.read();
        add_ln34_6_reg_249 = add_ln34_6_fu_175_p2.read();
        mul_ln34_1_reg_234 = mul_ln34_1_fu_137_p2.read();
        mul_ln34_2_reg_239 = mul_ln34_2_fu_151_p2.read();
        mul_ln34_3_reg_244 = mul_ln34_3_fu_165_p2.read();
        mul_ln34_4_reg_214 = mul_ln34_4_fu_86_p2.read();
        mul_ln34_5_reg_219 = mul_ln34_5_fu_100_p2.read();
        mul_ln34_6_reg_199 = mul_ln34_6_fu_44_p2.read();
        mul_ln34_7_reg_204 = mul_ln34_7_fu_58_p2.read();
        mul_ln34_8_reg_209 = mul_ln34_8_fu_72_p2.read();
        mul_ln34_reg_229 = mul_ln34_fu_123_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_int_reg = add_ln34_7_fu_194_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce.read())) {
        cal_conv_0_0_int_reg = cal_conv_0_0.read();
        cal_conv_0_1_int_reg = cal_conv_0_1.read();
        cal_conv_0_2_int_reg = cal_conv_0_2.read();
        cal_conv_1_0_int_reg = cal_conv_1_0.read();
        cal_conv_1_1_int_reg = cal_conv_1_1.read();
        cal_conv_1_2_int_reg = cal_conv_1_2.read();
        cal_conv_2_0_int_reg = cal_conv_2_0.read();
        cal_conv_2_1_int_reg = cal_conv_2_1.read();
        cal_conv_2_2_int_reg = cal_conv_2_2.read();
        kernel_0_0_int_reg = kernel_0_0.read();
        kernel_0_1_int_reg = kernel_0_1.read();
        kernel_0_2_int_reg = kernel_0_2.read();
        kernel_1_0_int_reg = kernel_1_0.read();
        kernel_1_1_int_reg = kernel_1_1.read();
        kernel_1_2_int_reg = kernel_1_2.read();
        kernel_2_0_int_reg = kernel_2_0.read();
        kernel_2_1_int_reg = kernel_2_1.read();
        kernel_2_2_int_reg = kernel_2_2.read();
    }
}

void single_conv_calculat::thread_add_ln34_1_fu_184_p2() {
    add_ln34_1_fu_184_p2 = (!mul_ln34_2_reg_239.read().is_01() || !mul_ln34_3_reg_244.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln34_2_reg_239.read()) + sc_biguint<32>(mul_ln34_3_reg_244.read()));
}

void single_conv_calculat::thread_add_ln34_2_fu_188_p2() {
    add_ln34_2_fu_188_p2 = (!add_ln34_1_fu_184_p2.read().is_01() || !add_ln34_fu_180_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln34_1_fu_184_p2.read()) + sc_biguint<32>(add_ln34_fu_180_p2.read()));
}

void single_conv_calculat::thread_add_ln34_3_fu_171_p2() {
    add_ln34_3_fu_171_p2 = (!mul_ln34_4_reg_214.read().is_01() || !mul_ln34_5_reg_219.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln34_4_reg_214.read()) + sc_biguint<32>(mul_ln34_5_reg_219.read()));
}

void single_conv_calculat::thread_add_ln34_4_fu_106_p2() {
    add_ln34_4_fu_106_p2 = (!mul_ln34_7_reg_204.read().is_01() || !mul_ln34_8_reg_209.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln34_7_reg_204.read()) + sc_biguint<32>(mul_ln34_8_reg_209.read()));
}

void single_conv_calculat::thread_add_ln34_5_fu_110_p2() {
    add_ln34_5_fu_110_p2 = (!add_ln34_4_fu_106_p2.read().is_01() || !mul_ln34_6_reg_199.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln34_4_fu_106_p2.read()) + sc_biguint<32>(mul_ln34_6_reg_199.read()));
}

void single_conv_calculat::thread_add_ln34_6_fu_175_p2() {
    add_ln34_6_fu_175_p2 = (!add_ln34_5_reg_224.read().is_01() || !add_ln34_3_fu_171_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln34_5_reg_224.read()) + sc_biguint<32>(add_ln34_3_fu_171_p2.read()));
}

void single_conv_calculat::thread_add_ln34_7_fu_194_p2() {
    add_ln34_7_fu_194_p2 = (!add_ln34_6_reg_249.read().is_01() || !add_ln34_2_fu_188_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln34_6_reg_249.read()) + sc_biguint<32>(add_ln34_2_fu_188_p2.read()));
}

void single_conv_calculat::thread_add_ln34_fu_180_p2() {
    add_ln34_fu_180_p2 = (!mul_ln34_reg_229.read().is_01() || !mul_ln34_1_reg_234.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln34_reg_229.read()) + sc_biguint<32>(mul_ln34_1_reg_234.read()));
}

void single_conv_calculat::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void single_conv_calculat::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void single_conv_calculat::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void single_conv_calculat::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void single_conv_calculat::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void single_conv_calculat::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void single_conv_calculat::thread_ap_return() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return = ap_return_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return = add_ln34_7_fu_194_p2.read();
    }
}

void single_conv_calculat::thread_mul_ln34_1_fu_137_p0() {
    mul_ln34_1_fu_137_p0 = cal_conv_0_1_int_reg.read();
}

void single_conv_calculat::thread_mul_ln34_1_fu_137_p1() {
    mul_ln34_1_fu_137_p1 = kernel_0_1_int_reg.read();
}

void single_conv_calculat::thread_mul_ln34_1_fu_137_p2() {
    mul_ln34_1_fu_137_p2 = (!mul_ln34_1_fu_137_p0.read().is_01() || !mul_ln34_1_fu_137_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln34_1_fu_137_p0.read()) * sc_bigint<32>(mul_ln34_1_fu_137_p1.read());
}

void single_conv_calculat::thread_mul_ln34_2_fu_151_p0() {
    mul_ln34_2_fu_151_p0 = cal_conv_0_2_int_reg.read();
}

void single_conv_calculat::thread_mul_ln34_2_fu_151_p1() {
    mul_ln34_2_fu_151_p1 = kernel_0_2_int_reg.read();
}

void single_conv_calculat::thread_mul_ln34_2_fu_151_p2() {
    mul_ln34_2_fu_151_p2 = (!mul_ln34_2_fu_151_p0.read().is_01() || !mul_ln34_2_fu_151_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln34_2_fu_151_p0.read()) * sc_bigint<32>(mul_ln34_2_fu_151_p1.read());
}

void single_conv_calculat::thread_mul_ln34_3_fu_165_p0() {
    mul_ln34_3_fu_165_p0 = cal_conv_1_0_int_reg.read();
}

void single_conv_calculat::thread_mul_ln34_3_fu_165_p1() {
    mul_ln34_3_fu_165_p1 = kernel_1_0_int_reg.read();
}

void single_conv_calculat::thread_mul_ln34_3_fu_165_p2() {
    mul_ln34_3_fu_165_p2 = (!mul_ln34_3_fu_165_p0.read().is_01() || !mul_ln34_3_fu_165_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln34_3_fu_165_p0.read()) * sc_bigint<32>(mul_ln34_3_fu_165_p1.read());
}

void single_conv_calculat::thread_mul_ln34_4_fu_86_p0() {
    mul_ln34_4_fu_86_p0 = cal_conv_1_1_int_reg.read();
}

void single_conv_calculat::thread_mul_ln34_4_fu_86_p1() {
    mul_ln34_4_fu_86_p1 = kernel_1_1_int_reg.read();
}

void single_conv_calculat::thread_mul_ln34_4_fu_86_p2() {
    mul_ln34_4_fu_86_p2 = (!mul_ln34_4_fu_86_p0.read().is_01() || !mul_ln34_4_fu_86_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln34_4_fu_86_p0.read()) * sc_bigint<32>(mul_ln34_4_fu_86_p1.read());
}

void single_conv_calculat::thread_mul_ln34_5_fu_100_p0() {
    mul_ln34_5_fu_100_p0 = cal_conv_1_2_int_reg.read();
}

void single_conv_calculat::thread_mul_ln34_5_fu_100_p1() {
    mul_ln34_5_fu_100_p1 = kernel_1_2_int_reg.read();
}

void single_conv_calculat::thread_mul_ln34_5_fu_100_p2() {
    mul_ln34_5_fu_100_p2 = (!mul_ln34_5_fu_100_p0.read().is_01() || !mul_ln34_5_fu_100_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln34_5_fu_100_p0.read()) * sc_bigint<32>(mul_ln34_5_fu_100_p1.read());
}

void single_conv_calculat::thread_mul_ln34_6_fu_44_p0() {
    mul_ln34_6_fu_44_p0 = cal_conv_2_0_int_reg.read();
}

void single_conv_calculat::thread_mul_ln34_6_fu_44_p1() {
    mul_ln34_6_fu_44_p1 = kernel_2_0_int_reg.read();
}

void single_conv_calculat::thread_mul_ln34_6_fu_44_p2() {
    mul_ln34_6_fu_44_p2 = (!mul_ln34_6_fu_44_p0.read().is_01() || !mul_ln34_6_fu_44_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln34_6_fu_44_p0.read()) * sc_bigint<32>(mul_ln34_6_fu_44_p1.read());
}

void single_conv_calculat::thread_mul_ln34_7_fu_58_p0() {
    mul_ln34_7_fu_58_p0 = cal_conv_2_1_int_reg.read();
}

void single_conv_calculat::thread_mul_ln34_7_fu_58_p1() {
    mul_ln34_7_fu_58_p1 = kernel_2_1_int_reg.read();
}

void single_conv_calculat::thread_mul_ln34_7_fu_58_p2() {
    mul_ln34_7_fu_58_p2 = (!mul_ln34_7_fu_58_p0.read().is_01() || !mul_ln34_7_fu_58_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln34_7_fu_58_p0.read()) * sc_bigint<32>(mul_ln34_7_fu_58_p1.read());
}

void single_conv_calculat::thread_mul_ln34_8_fu_72_p0() {
    mul_ln34_8_fu_72_p0 = cal_conv_2_2_int_reg.read();
}

void single_conv_calculat::thread_mul_ln34_8_fu_72_p1() {
    mul_ln34_8_fu_72_p1 = kernel_2_2_int_reg.read();
}

void single_conv_calculat::thread_mul_ln34_8_fu_72_p2() {
    mul_ln34_8_fu_72_p2 = (!mul_ln34_8_fu_72_p0.read().is_01() || !mul_ln34_8_fu_72_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln34_8_fu_72_p0.read()) * sc_bigint<32>(mul_ln34_8_fu_72_p1.read());
}

void single_conv_calculat::thread_mul_ln34_fu_123_p0() {
    mul_ln34_fu_123_p0 = cal_conv_0_0_int_reg.read();
}

void single_conv_calculat::thread_mul_ln34_fu_123_p1() {
    mul_ln34_fu_123_p1 = kernel_0_0_int_reg.read();
}

void single_conv_calculat::thread_mul_ln34_fu_123_p2() {
    mul_ln34_fu_123_p2 = (!mul_ln34_fu_123_p0.read().is_01() || !mul_ln34_fu_123_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln34_fu_123_p0.read()) * sc_bigint<32>(mul_ln34_fu_123_p1.read());
}

}

