// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module single_conv_calculat (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        cal_conv_address0,
        cal_conv_ce0,
        cal_conv_q0,
        kernel_address0,
        kernel_ce0,
        kernel_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] cal_conv_address0;
output   cal_conv_ce0;
input  [31:0] cal_conv_q0;
output  [3:0] kernel_address0;
output   kernel_ce0;
input  [31:0] kernel_q0;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg cal_conv_ce0;
reg kernel_ce0;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] i_fu_98_p2;
reg   [1:0] i_reg_177;
wire    ap_CS_fsm_state2;
wire   [4:0] sub_ln34_fu_120_p2;
reg   [4:0] sub_ln34_reg_182;
wire   [0:0] icmp_ln30_fu_92_p2;
wire   [1:0] j_fu_132_p2;
reg   [1:0] j_reg_190;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln32_fu_126_p2;
reg  signed [31:0] cal_conv_load_reg_205;
wire    ap_CS_fsm_state4;
reg  signed [31:0] kernel_load_reg_210;
wire   [31:0] mul_ln34_fu_153_p2;
reg   [31:0] mul_ln34_reg_215;
wire    ap_CS_fsm_state5;
reg   [1:0] i_0_reg_62;
reg   [1:0] j_0_reg_73;
wire    ap_CS_fsm_state6;
wire  signed [63:0] sext_ln34_fu_147_p1;
reg   [31:0] ans_1_fu_32;
wire   [31:0] ans_fu_157_p2;
wire   [3:0] tmp_s_fu_108_p3;
wire   [4:0] zext_ln34_1_fu_116_p1;
wire   [4:0] zext_ln34_fu_104_p1;
wire   [4:0] zext_ln34_2_fu_138_p1;
wire   [4:0] add_ln34_fu_142_p2;
reg   [5:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ans_1_fu_32 <= ans_fu_157_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        ans_1_fu_32 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln32_fu_126_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_0_reg_62 <= i_reg_177;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_62 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        j_0_reg_73 <= j_reg_190;
    end else if (((icmp_ln30_fu_92_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_0_reg_73 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        cal_conv_load_reg_205 <= cal_conv_q0;
        kernel_load_reg_210 <= kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_177 <= i_fu_98_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        j_reg_190 <= j_fu_132_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mul_ln34_reg_215 <= mul_ln34_fu_153_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln30_fu_92_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        sub_ln34_reg_182 <= sub_ln34_fu_120_p2;
    end
end

always @ (*) begin
    if ((((icmp_ln30_fu_92_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln30_fu_92_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        cal_conv_ce0 = 1'b1;
    end else begin
        cal_conv_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_ce0 = 1'b1;
    end else begin
        kernel_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln30_fu_92_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln32_fu_126_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln34_fu_142_p2 = (sub_ln34_reg_182 + zext_ln34_2_fu_138_p1);

assign ans_fu_157_p2 = (ans_1_fu_32 + mul_ln34_reg_215);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_return = ans_1_fu_32;

assign cal_conv_address0 = sext_ln34_fu_147_p1;

assign i_fu_98_p2 = (i_0_reg_62 + 2'd1);

assign icmp_ln30_fu_92_p2 = ((i_0_reg_62 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_126_p2 = ((j_0_reg_73 == 2'd3) ? 1'b1 : 1'b0);

assign j_fu_132_p2 = (j_0_reg_73 + 2'd1);

assign kernel_address0 = sext_ln34_fu_147_p1;

assign mul_ln34_fu_153_p2 = ($signed(kernel_load_reg_210) * $signed(cal_conv_load_reg_205));

assign sext_ln34_fu_147_p1 = $signed(add_ln34_fu_142_p2);

assign sub_ln34_fu_120_p2 = (zext_ln34_1_fu_116_p1 - zext_ln34_fu_104_p1);

assign tmp_s_fu_108_p3 = {{i_0_reg_62}, {2'd0}};

assign zext_ln34_1_fu_116_p1 = tmp_s_fu_108_p3;

assign zext_ln34_2_fu_138_p1 = j_0_reg_73;

assign zext_ln34_fu_104_p1 = i_0_reg_62;

endmodule //single_conv_calculat
